# Generated by Django 5.2 on 2025-04-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGoal',
        ),
    ]
