# Generated by Django 5.2 on 2025-04-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_add_sample_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
